export {
  HIVE_CREW_BROWSER_DESCRIPTION,
  HIVE_CREW_BROWSER_TITLE,
  HIVE_CREW_DESKTOP_APP_ID,
  HIVE_CREW_DESKTOP_PROTOCOL,
  HIVE_CREW_LEGACY_DESKTOP_PROTOCOLS,
  HIVE_CREW_LOCAL_ENDPOINTS,
  HIVE_CREW_PRODUCT,
  HIVE_CREW_PRODUCT_NAME,
  HIVE_CREW_WORKSPACE_FALLBACK_HOST,
} from "./identity";
